### ISSUE TITLE
Improve PDF build and add deployment feature

### ISSUE THREAD

**Issue by johannchopin** [systemtechniklabor/htwsaar-i-mst-vorlage#8]
Hi team 👋 

For my own purpose I updated the Github Action script so that it can deploy the builded PDF on the Github Pages service. The idea is that on each push to the `main` branch, the pdf is build and made accessible online with a simple URL. Here is the updated action:

```yml
name: Build and Deploy
on:
  push:
    branches:
      - main
permissions: 
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: 🤖 Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: my-file.tex
          post_compile: "mkdir build && mv my-file.pdf build"

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
```

You can have a look at the working example https://github.com/johannchopin/master-degree-thesis-paper.

If you like the idea I will submit a PR.
